apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
  namespace: bb-mpc
spec:
  action: pod-kill
  mode: fixed
  value: '2'
  selector:
    labelSelectors:
      app: bb-mpc
  scheduler:
    cron: "@every 20s"